### ISSUE TITLE
Some string inputs throw or are incorrect

### ISSUE THREAD

**Issue by GrantGryczan** [gilbarbara/react-from-dom#15] opened 2021-09-07 09:33 UTC
Examples:

* Input: `convert('test')`
Expected output (approximate): `'test'`
Actual output: `null`, throws `new Error('Error parsing input')`

* Input: `convert('1<span>2</span>3')`
Expected output (approximate): `['1', <span>2</span>, '3']`
Actual output: `<span>3</span>`

I don't actually use the feature that allows strings to be converted (if I wanted to do only that, I would just use [html-react-parser](https://github.com/remarkablemark/html-react-parser)), so I don't need this to be fixed, but I figured it would be good to report regardless.

**Comment by gilbarbara** [comment] 2021-09-08 00:05
hey @GrantGryczan 

`convert('test')` does throw, but this library ignores text nodes by design.
`convert('1<span>2</span>3')` returns a span element with `2` as expected (text nodes are ignored).

**Comment by GrantGryczan** [comment] 2021-09-08 00:22
Huh, alright then. Why have you decided to ignore text nodes?

**Comment by gilbarbara** [comment] 2021-09-08 00:32
To be unopinionated.
Text nodes without a parent would have to be rendered as spans, is that correct?
And the actions can be used to change the behavior if the user needs it.

**Comment by GrantGryczan** [comment] 2021-09-08 01:53
> Text nodes without a parent would have to be rendered as spans, is that correct?

No that is not correct. React can render arrays, which is a conventional way to render a set of multiple nodes without any parent element. React also supports strings, which are the React equivalent of a text node, and they can be rendered directly without a parent element as well.

`string` extends `ReactNode`, as does `string[]`. So `'hello world'` is a valid `ReactNode`, and `['hello', ' ', 'world']` is as well. You don't need to pick an arbitrary element to wrap them in--it wouldn't be opinionated.

**Comment by gilbarbara** [comment] 2024-02-27 23:43
Fixed in 0.7.0

**Closed as completed by gilbarbara** 2024-02-27 23:43 UTC
